# Generated by Django 4.2.14 on 2024-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Department_code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('confirm_Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='batch',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='girls_hostel_master',
            name='quota',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='boys_hostel_master',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
