# Generated by Django 5.0.1 on 2024-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0003_booking_admissionno_booking_gm_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admissionNo_year", models.CharField(max_length=100)),
                ("ammount", models.IntegerField()),
                ("proof", models.CharField(max_length=100)),
            ],
        ),
    ]
