# Generated by Django 5.0.1 on 2024-08-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0004_fees"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fees",
            old_name="ammount",
            new_name="amount",
        ),
    ]
